INSERT INTO brand (brand_id, name) VALUES (1, 'A');
INSERT INTO brand (brand_id, name) VALUES (2, 'B');
INSERT INTO brand (brand_id, name) VALUES (3, 'C');
INSERT INTO brand (brand_id, name) VALUES (4, 'D');
INSERT INTO brand (brand_id, name) VALUES (5, 'E');
INSERT INTO brand (brand_id, name) VALUES (6, 'F');
INSERT INTO brand (brand_id, name) VALUES (7, 'G');
INSERT INTO brand (brand_id, name) VALUES (8, 'H');
INSERT INTO brand (brand_id, name) VALUES (9, 'I');

INSERT INTO product (brand_id, category_name, price) VALUES (1, '상의', 11200);
INSERT INTO product (brand_id, category_name, price) VALUES (1, '아우터', 5500);
INSERT INTO product (brand_id, category_name, price) VALUES (1, '바지', 4200);
INSERT INTO product (brand_id, category_name, price) VALUES (1, '스니커즈', 9000);
INSERT INTO product (brand_id, category_name, price) VALUES (1, '가방', 2000);
INSERT INTO product (brand_id, category_name, price) VALUES (1, '모자', 1700);
INSERT INTO product (brand_id, category_name, price) VALUES (1, '양말', 1800);
INSERT INTO product (brand_id, category_name, price) VALUES (1, '액세서리', 2300);
INSERT INTO product (brand_id, category_name, price) VALUES (2, '상의', 10500);
INSERT INTO product (brand_id, category_name, price) VALUES (2, '아우터', 5900);
INSERT INTO product (brand_id, category_name, price) VALUES (2, '바지', 3800);
INSERT INTO product (brand_id, category_name, price) VALUES (2, '스니커즈', 9100);
INSERT INTO product (brand_id, category_name, price) VALUES (2, '가방', 2100);
INSERT INTO product (brand_id, category_name, price) VALUES (2, '모자', 2000);
INSERT INTO product (brand_id, category_name, price) VALUES (2, '양말', 2000);
INSERT INTO product (brand_id, category_name, price) VALUES (2, '액세서리', 2200);
INSERT INTO product (brand_id, category_name, price) VALUES (3, '상의', 10000);
INSERT INTO product (brand_id, category_name, price) VALUES (3, '아우터', 6200);
INSERT INTO product (brand_id, category_name, price) VALUES (3, '바지', 3300);
INSERT INTO product (brand_id, category_name, price) VALUES (3, '스니커즈', 9200);
INSERT INTO product (brand_id, category_name, price) VALUES (3, '가방', 2200);
INSERT INTO product (brand_id, category_name, price) VALUES (3, '모자', 1900);
INSERT INTO product (brand_id, category_name, price) VALUES (3, '양말', 2200);
INSERT INTO product (brand_id, category_name, price) VALUES (3, '액세서리', 2100);
INSERT INTO product (brand_id, category_name, price) VALUES (4, '상의', 10100);
INSERT INTO product (brand_id, category_name, price) VALUES (4, '아우터', 5100);
INSERT INTO product (brand_id, category_name, price) VALUES (4, '바지', 3000);
INSERT INTO product (brand_id, category_name, price) VALUES (4, '스니커즈', 9500);
INSERT INTO product (brand_id, category_name, price) VALUES (4, '가방', 2500);
INSERT INTO product (brand_id, category_name, price) VALUES (4, '모자', 1500);
INSERT INTO product (brand_id, category_name, price) VALUES (4, '양말', 2400);
INSERT INTO product (brand_id, category_name, price) VALUES (4, '액세서리', 2000);
INSERT INTO product (brand_id, category_name, price) VALUES (5, '상의', 10700);
INSERT INTO product (brand_id, category_name, price) VALUES (5, '아우터', 5000);
INSERT INTO product (brand_id, category_name, price) VALUES (5, '바지', 3800);
INSERT INTO product (brand_id, category_name, price) VALUES (5, '스니커즈', 9900);
INSERT INTO product (brand_id, category_name, price) VALUES (5, '가방', 2300);
INSERT INTO product (brand_id, category_name, price) VALUES (5, '모자', 1800);
INSERT INTO product (brand_id, category_name, price) VALUES (5, '양말', 2100);
INSERT INTO product (brand_id, category_name, price) VALUES (5, '액세서리', 2100);
INSERT INTO product (brand_id, category_name, price) VALUES (6, '상의', 11200);
INSERT INTO product (brand_id, category_name, price) VALUES (6, '아우터', 7200);
INSERT INTO product (brand_id, category_name, price) VALUES (6, '바지', 4000);
INSERT INTO product (brand_id, category_name, price) VALUES (6, '스니커즈', 9300);
INSERT INTO product (brand_id, category_name, price) VALUES (6, '가방', 2100);
INSERT INTO product (brand_id, category_name, price) VALUES (6, '모자', 1600);
INSERT INTO product (brand_id, category_name, price) VALUES (6, '양말', 2300);
INSERT INTO product (brand_id, category_name, price) VALUES (6, '액세서리', 1900);
INSERT INTO product (brand_id, category_name, price) VALUES (7, '상의', 10500);
INSERT INTO product (brand_id, category_name, price) VALUES (7, '아우터', 5800);
INSERT INTO product (brand_id, category_name, price) VALUES (7, '바지', 3900);
INSERT INTO product (brand_id, category_name, price) VALUES (7, '스니커즈', 9000);
INSERT INTO product (brand_id, category_name, price) VALUES (7, '가방', 2200);
INSERT INTO product (brand_id, category_name, price) VALUES (7, '모자', 1700);
INSERT INTO product (brand_id, category_name, price) VALUES (7, '양말', 2100);
INSERT INTO product (brand_id, category_name, price) VALUES (7, '액세서리', 2000);
INSERT INTO product (brand_id, category_name, price) VALUES (8, '상의', 10800);
INSERT INTO product (brand_id, category_name, price) VALUES (8, '아우터', 6300);
INSERT INTO product (brand_id, category_name, price) VALUES (8, '바지', 3100);
INSERT INTO product (brand_id, category_name, price) VALUES (8, '스니커즈', 9700);
INSERT INTO product (brand_id, category_name, price) VALUES (8, '가방', 2400);
INSERT INTO product (brand_id, category_name, price) VALUES (8, '모자', 1500);
INSERT INTO product (brand_id, category_name, price) VALUES (8, '양말', 2200);
INSERT INTO product (brand_id, category_name, price) VALUES (8, '액세서리', 2100);
INSERT INTO product (brand_id, category_name, price) VALUES (9, '상의', 10600);
INSERT INTO product (brand_id, category_name, price) VALUES (9, '아우터', 5500);
INSERT INTO product (brand_id, category_name, price) VALUES (9, '바지', 3500);
INSERT INTO product (brand_id, category_name, price) VALUES (9, '스니커즈', 9400);
INSERT INTO product (brand_id, category_name, price) VALUES (9, '가방', 2100);
INSERT INTO product (brand_id, category_name, price) VALUES (9, '모자', 1600);
INSERT INTO product (brand_id, category_name, price) VALUES (9, '양말', 2300);
INSERT INTO product (brand_id, category_name, price) VALUES (9, '액세서리', 1900);

